import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css'; // Import react-toastify CSS
import { ToastContainer } from 'react-toastify'; // Import ToastContainer
import Navbar from "./components/Navbar/Navbar";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookKeeper",
  description: "Generated by Sikandar Shahbaz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <ToastContainer 
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light" // or "dark" or "colored"
          />
          <Navbar />
          {/* Add background color to main to prevent body bg showing in padding */}
          <main style={{ paddingTop: '70px', backgroundColor: '#f8f9fa' }}> 
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
